"""add migration_id_mappings table

Revision ID: 6a1ed2a6f5be
Revises: a973ce311ce7
Create Date: 2026-02-24 17:26:00.408484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1ed2a6f5be'
down_revision: Union[str, None] = 'a973ce311ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_id_mappings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'source_id', name='uq_entity_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migration_id_mappings')
    # ### end Alembic commands ###
